name: "Zephyr West"
description: 'Action incorporating Zephyr dependencies and West build tool'
branding:
  icon: 'play'
  color: 'purple'
inputs:
  command:  # id of input
    description: 'Which west command to execute'
    required: true
    default: 'build'
  command-args:  # id of input
    description: 'Extra arguments for the west command'
    required: false
  working-directory: # id of input
    description: "Working directory for west command"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
    - ${{ inputs.command-args }}
    - ${{ inputs.working-directory }}
